### ISSUE TITLE
Link to LICENSE is broken

### ISSUE THREAD

**Issue by sharedbyayla** [neeraj15022001/Profile.md#8]
The link to the LICENSE in the README.md file is broken. 

To fix this issue, the link should be updated from:
```
https://github.com/neeraj15022001/Profile.md/blob/master/LICENSE.md
```

To:
```
https://github.com/neeraj15022001/Profile.md/blob/master/LICENSE
```

![Screen Shot 2021-10-06 at 9 53 14 AM](https://user-images.githubusercontent.com/54963017/136216927-a710c596-c298-4a58-b077-8cfd00795cb9.png)

**Comment by sharedbyayla** [comment]
Hello! I apologize for not yet reading the CONTRIBUTING.md and CODE_OF_CONDUCT.md files that were mentioned as requirements for contributing to this project, but it seems those files have not yet been added (see issues #6 and #7). I will certainly keep an eye out for them. 

In the meantime, I was hoping to help out by working on this small issue. Please let me know if that would be okay or if you'd like me to wait for the CONTRIBUTING.md and CODE_OF_CONDUCT.md files to be added :)

**Comment by neeraj15022001** [comment]
Hey @aexcode i just saw these issues created by you and i already fixed them, they are now working. In case you want to contribute anything else towards website you can open an issue or you can contribute to our main repository.
Repository Link - https://github.com/victor-thescuti/Profile.md
Website - https://profilemd.vercel.app/
For Now i am closing these issues.
Have a nice day. Happy Open Sourcing!!!!
